configuration:
  runtime: concord-v2

flows:
  onPush:
    - name: "Github Event"
      log: "${resource.prettyPrintYaml(event)}"

triggers:
  - github:
      entryPoint: onPush
      version: 2
      conditions:
        type: push
        files:
          modified:
            - "components/.*"