configuration:
  runtime: concord-v2

flows:
  onPush:
    - log: ${event}

triggers:
  - github:
      entryPoint: onPush
      version: 2
      conditions:
        type: push
        files:
          modified:
            - "components/.*"