flows:
  default:
    - log: "Hello, 1"
  
  onKittUpdate:
    - log: "kitt update, ${event}"
    
triggers:
- github:
    entryPoint: "onKittUpdate"
    conditions:
      type: "push"
      branch: "master"
      files:
        modified:
          - "kitt.yml"
