configuration:
  runtime: concord-v2
  
flows:
  onCron:
  - log: "initiator: ${initiator}"


triggers:
  - cron:
      spec: "* * * * *"
      entryPoint: onCron
      runAs:
         withSecret: "test-run-as"
