configuration:
  runtime: concord-v2

flows:
  onPush:
    - name: "Modified files"
      log: "${event.files.modified}"
      
    - name: "Github Event"
      log: "${resource.prettyPrintYaml(event)}"

triggers:
  - github:
      entryPoint: onPush
      version: 2
      conditions:
        type: push
        githubRepo:
          - firstRepo
          - secondRepo        
