flows:
  default:
    - log: "Hello, 1"
  
  registerKittRepoifNeeded:
    - log: "kitt, ${event.repository.fullName}"
    
triggers:
- github:
    entryPoint: "registerKittRepoifNeeded"
    conditions:
      type: "push"
      branch: ".*"
      githubOrg: ".*"
      githubRepo: ".*"
      files:
        added:
          - "kitt.yml"
